### ISSUE TITLE
Erro ao tentar abrir o editor do digrama

### ISSUE THREAD

**Issue by Fel3180** [lizardoluis/omtg-designer#14]
![erro](https://cloud.githubusercontent.com/assets/27966524/25346913/8d342cb6-28ef-11e7-9a42-87695d42dee8.PNG)

Pelo que notei está dando um erro de propriedade não encontrada "getTooltip".

Felipe de Oliveira Silva - Aluno do PPGC - Disciplina BDG - Clodoveu

**Comment by lizardoluis** [comment]
+ 0.5
Já corrigido.
Obrigado
