### ISSUE TITLE
erro no diagrama ao importar projeto

### ISSUE THREAD

**Issue by lcrcosta** [lizardoluis/omtg-designer#15]
Luiz,

Ao importar um projeto com generalização, o conector não está ficando conectado na classe pai. 

Parabéns pela ferramenta.
Abraços.

![bugomtg](https://cloud.githubusercontent.com/assets/28014966/25397339/4fc3ad8c-29be-11e7-8f10-f46c597aeba7.PNG)

**Comment by lizardoluis** [comment]
Oi @lcrcosta,
Você pode me passar o XML do projeto?

Grato

**Comment by lcrcosta** [comment]
Claro, segue.


Abr.,
Luiz Carlos R Costa, PMP® 

    Em Terça-feira, 25 de Abril de 2017 16:51, Luís Lizardo <notifications@github.com> escreveu:
 

 Oi @lcrcosta,
Você pode me passar o XML do projeto?Grato—

**Comment by lizardoluis** [comment]
Cade o anexo? Não recebi o XML

**Comment by lcrcosta** [comment]
deve ter sido bloqueado.anexei como zip.
 
Abr.,
Luiz Carlos R Costa, PMP® 

    Em Terça-feira, 25 de Abril de 2017 18:42, Luís Lizardo <notifications@github.com> escreveu:
 

 Cade o anexo? Não recebi o XML—

**Comment by lizardoluis** [comment]
@lcrcosta ainda não consegui receber o arquivo. 
Mande por favor no meu email lizardo.luis@gmail.com

**Comment by lizardoluis** [comment]
@lcrcosta bug corrigido, obrigado pelo report.
'+' 0.5 pts em BDG

A proposito, vi que no seu projeto você tem criado atributos para as chaves estrangeiras de relacionamentos convencionais. Isso é desnecessário na modelagem, pois está implícito no relacionamento, e ao exportar para SQL, a ferramenta adiciona as devidas chaves estrangeiras. Como exemplo, você criou o atributo "agency_id" na tabela "route".

**Comment by lcrcosta** [comment]
Obrigado Luis.Parabéns pelo trabalho, ferramenta mão-na-roda.
Valeu pela dia. 
Abr.,
Luiz Carlos R Costa, PMP® 

    Em Quinta-feira, 27 de Abril de 2017 13:53, Luís Lizardo <notifications@github.com> escreveu:
 

 @lcrcosta bug corrigido, obrigado pelo report.
'+' 0.5 pts em BDGA proposito, vi que no seu projeto você tem criado atributos para as chaves estrangeiras de relacionamentos convencionais. Isso é desnecessário na modelagem, pois está implícito no relacionamento, e ao exportar para SQL, a ferramenta adiciona as devidas chaves estrangeiras. Como exemplo, você criou o atributo "agency_id" na tabela "route".—
