### ISSUE TITLE
Colocar nome das tabelas referentes as cardinalidades no editor de relacionamentos.

### ISSUE THREAD

**Issue by lcrcosta** [lizardoluis/omtg-designer#17]
A sugestão é para que no modal "Connection Editor"  trazer os nomes das tabelas em "Cardinality A:" e "Cardinality B:".
Como na ferramenta a direção da criação da associação não é importante, o lado A e B variam a todo instante e os nomes das tabelas ajudam no processo, evitando de ter que sair e/ou refazer o conector.
abraço.

**Comment by lizardoluis** [comment]
Boa sugestão @lcrcosta. Vou colocar na lista de coisas a fazer. Mas não conta como bug pra aula de BDG.
Grato

**Comment by lizardoluis** [comment]
@lcrcosta implementei sua sugestão.
Obrigado.
