### ISSUE TITLE
Auto relacionamento em associações

### ISSUE THREAD

**Issue by KarineVersieux** [lizardoluis/omtg-designer#18]
Luis, 

Não estou conseguindo criar auto-relacionamentos. A ferramenta permite ?

Karine.

**Comment by lizardoluis** [comment]
Oi Karine,

A ferramenta permite apenas numa rede arco-arco (Como a figura abaixo). Não sei se faz sentido outros tipos de relacionamentos, como a associação. Vou conversar com o Clodoveu sobre. 

Caso sim, te dou os pontos, porque seria um bug.

![image](https://cloud.githubusercontent.com/assets/2699897/25686303/98dcca04-3043-11e7-8103-8232f09edce5.png)

Att.

**Comment by lizardoluis** [comment]
@KarineVersieux,

Conversei com o Clodoveu e de fato é necessário sim permitir auto-relacionamento de associações convencionais. No entanto, estamos discutindo ainda se nas associações espaciais faz sentido.

Seu report não é bem um bug da ferramenta, mas é uma melhoria importante e necessária a ser implementada. Por isso você tem direito aos 0.5 pontinhos extras em BDG.

Obrigado pelo report.

**Comment by KarineVersieux** [comment]
ok @lizardoluis.  Obrigada.

**Comment by lizardoluis** [comment]
Pronto @KarineVersieux, agora é possível fazer-auto relacionamentos para associações convencionais. 

![image](https://cloud.githubusercontent.com/assets/2699897/25832703/9378fd14-3442-11e7-98c6-3707a083edbf.png)
