### ISSUE TITLE
comentários

### ISSUE THREAD

**Issue by lcrcosta** [lizardoluis/omtg-designer#19]
Luis,
Mais uma dica, é permitir a adição de comentários junto com os atributos. Não precisam estar visíveis.
Mas, para montar um dicionário de dados os comentários quando já descritos junto aos atributos, no export para o banco facilita bastante.
Abraço.

**Comment by lizardoluis** [comment]
Como assim?

**Comment by lizardoluis** [comment]
@lcrcosta

**Comment by lcrcosta** [comment]
Luis,
Eu novamente.Estou tentando importar o script gerado para postgis. Mas, estou tendo algumas dificuldades.É minha primeira vez com o postgis, então não sei se instalei ou se deveria funcionar do jeito que está.Já tomei a liberdade e anexei o sql, se puder testar no seu ambiente e me falar que está correto eu saberia que o problema está no meu.Por exemplo.: Essa definição de atributo está correta? ... geom ast_node,
Não deveria ser "geom geometry," ?
Se puder me ajudar nessa agradeço.

Abr.,
Luiz Carlos R Costa, PMP® 

    Em Segunda-feira, 15 de Maio de 2017 21:26, Luís Lizardo <notifications@github.com> escreveu:
 

 @lcrcosta—

**Comment by lcrcosta** [comment]
esqueci o anexo. 
coloquei como txt para nao ser barrado no email.mais uma vez, obrigado. 
Abr.,
Luiz Carlos R Costa, PMP® 

    Em Quarta-feira, 17 de Maio de 2017 23:03, Luiz Carlos Rodrigues Costa <lc_rcosta@yahoo.com.br> escreveu:
 

 Luis,
Eu novamente.Estou tentando importar o script gerado para postgis. Mas, estou tendo algumas dificuldades.É minha primeira vez com o postgis, então não sei se instalei ou se deveria funcionar do jeito que está.Já tomei a liberdade e anexei o sql, se puder testar no seu ambiente e me falar que está correto eu saberia que o problema está no meu.Por exemplo.: Essa definição de atributo está correta? ... geom ast_node,
Não deveria ser "geom geometry," ?
Se puder me ajudar nessa agradeço.

Abr.,
Luiz Carlos R Costa, PMP® 

    Em Segunda-feira, 15 de Maio de 2017 21:26, Luís Lizardo <notifications@github.com> escreveu:
 

 @lcrcosta—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.  

   

   
-- Create table stop
CREATE TABLE stop (
  id_stop INTEGER,
  stop_id VARCHAR(100),
  stop_code VARCHAR(50) NOT NULL,
  stop_name VARCHAR(255),
  stop_desc VARCHAR(4000) NOT NULL,
  zone_id INTEGER NOT NULL,
  stop_url VARCHAR(4000) NOT NULL,
  stop_timezone VARCHAR(20) NOT NULL,
  wheelchair_boarding INTEGER NOT NULL,
  id_feed INTEGER,
  id_station INTEGER,
  geom ast_node,
  CONSTRAINT pk_stop PRIMARY KEY (id_stop)
);

-- Create the spatial index on geom column of stop
CREATE INDEX SIDX_stop
  ON stop
  USING GIST (geom);

-- Create table trip_line
CREATE TABLE trip_line (
  geom ast_uniline
);

-- Create the spatial index on geom column of trip_line
CREATE INDEX SIDX_trip_line
  ON trip_line
  USING GIST (geom);

-- Create table transfer
CREATE TABLE transfer (
  id_stop_from INTEGER,
  id_stop_to INTEGER,
  transfer_type INTEGER,
  min_transfer_time INTEGER NOT NULL,
  CONSTRAINT pk_transfer PRIMARY KEY (id_stop_from,id_stop_to)
);

-- Create table station
CREATE TABLE station (
  id_station INTEGER,
  station_id VARCHAR(100),
  station_code VARCHAR(50) NOT NULL,
  station_name VARCHAR(255),
  station_desc VARCHAR(400) NOT NULL,
  wheelchairboarding INTEGER NOT NULL,
  station_timezone VARCHAR(20) NOT NULL,
  id_feed INTEGER,
  geom ast_polygon,
  CONSTRAINT pk_station PRIMARY KEY (id_station)
);

-- Create the spatial index on geom column of station
CREATE INDEX SIDX_station
  ON station
  USING GIST (geom);

-- Create table stop_time
CREATE TABLE stop_time (
  id_stop INTEGER,
  stop_sequence INTEGER,
  arrival_time TIME,
  departure_time TIME,
  stop_headsign VARCHAR(255),
  pickup_type INTEGER NOT NULL,
  drop_off_type INTEGER NOT NULL,
  shape_dist_traveled INTEGER NOT NULL,
  timepoint INTEGER,
  id_trip INTEGER,
  CONSTRAINT pk_stop_time PRIMARY KEY (id_stop,stop_sequence)
);

-- Create table fare_attribute
CREATE TABLE fare_attribute (
  id_fare INTEGER,
  fare_id VARCHAR(100),
  price REAL,
  currency_type VARCHAR(50),
  payment_method INTEGER,
  transfers INTEGER,
  transfer_duration INTEGER NOT NULL,
  id_agency INTEGER,
  CONSTRAINT pk_fare_attribute PRIMARY KEY (id_fare)
);

-- Create table agency
CREATE TABLE agency (
  id_agency INTEGER,
  agency_id VARCHAR(100),
  agency_name VARCHAR(255),
  agency_url VARCHAR(4000),
  agency_timezone VARCHAR(100),
  agency_lang VARCHAR(50) NOT NULL,
  agency_phone VARCHAR(20) NOT NULL,
  agency_fare_url VARCHAR(4000) NOT NULL,
  agency_email VARCHAR(255) NOT NULL,
  id_feed INTEGER,
  CONSTRAINT pk_agency PRIMARY KEY (id_agency)
);

-- Create table frequency
CREATE TABLE frequency (
  id_frequency INTEGER,
  start_time TIME,
  end_time INTEGER,
  headway_secs INTEGER,
  exact_times INTEGER NOT NULL,
  id_trip INTEGER,
  CONSTRAINT pk_frequency PRIMARY KEY (id_frequency)
);

-- Create table feed_info
CREATE TABLE feed_info (
  id_feed INTEGER,
  feed_publisher_name VARCHAR(255),
  feed_publisher_url VARCHAR(4000),
  feed_lang TEXT,
  feed_start_date DATE NOT NULL,
  feed_end_date DATE NOT NULL,
  feed_version VARCHAR(50) NOT NULL,
  CONSTRAINT pk_feed_info PRIMARY KEY (id_feed)
);

-- Create table entrance
CREATE TABLE entrance (
  id_entrance INTEGER,
  id_station INTEGER,
  geom ast_point,
  CONSTRAINT pk_entrance PRIMARY KEY (id_entrance)
);

-- Create the spatial index on geom column of entrance
CREATE INDEX SIDX_entrance
  ON entrance
  USING GIST (geom);

-- Create table calendar_date
CREATE TABLE calendar_date (
  id_service INTEGER,
  date DATE,
  exception_type INTEGER,
  CONSTRAINT pk_calendar_date PRIMARY KEY (id_service,date)
);

-- Create table route
CREATE TABLE route (
  id_route INTEGER,
  route_id VARCHAR(100),
  route_short_name VARCHAR(255),
  route_long_name VARCHAR(255),
  route_desc VARCHAR(4000) NOT NULL,
  route_type INTEGER,
  route_url VARCHAR(4000) NOT NULL,
  route_color VARCHAR(6) NOT NULL,
  route_text_color VARCHAR(6) NOT NULL,
  id_feed INTEGER,
  id_agency INTEGER,
  CONSTRAINT pk_route PRIMARY KEY (id_route)
);

-- Create table service
CREATE TABLE service (
  id_service INTEGER,
  service_id VARCHAR(100),
  CONSTRAINT pk_service PRIMARY KEY (id_service)
);

-- Create table trip
CREATE TABLE trip (
  id_trip INTEGER,
  trip_id VARCHAR(100),
  trip_headsign VARCHAR(255) NOT NULL,
  trip_short_name VARCHAR(255) NOT NULL,
  direction_id INTEGER NOT NULL,
  block_id INTEGER NOT NULL,
  wheelchair_accessible INTEGER NOT NULL,
  bikes_allowed INTEGER NOT NULL,
  id_route INTEGER,
  CONSTRAINT pk_trip PRIMARY KEY (id_trip)
);

-- Create table fare_rule
CREATE TABLE fare_rule (
  id_fare_rule INTEGER,
  id_fare INTEGER,
  id_route INTEGER,
  orign_id INTEGER,
  destination_id INTEGER,
  contains_id INTEGER,
  id_feed INTEGER,
  CONSTRAINT pk_fare_rule PRIMARY KEY (id_fare_rule)
);

-- Create table zone
CREATE TABLE zone (
  zone_id INTEGER,
  id_feed INTEGER,
  geom ast_polygon,
  CONSTRAINT pk_zone PRIMARY KEY (zone_id,id_feed)
);

-- Create the spatial index on geom column of zone
CREATE INDEX SIDX_zone
  ON zone
  USING GIST (geom);

-- Create table calendar
CREATE TABLE calendar (
  id_service INTEGER,
  monday INTEGER,
  tuesday INTEGER,
  wednesday INTEGER,
  thursday INTEGER,
  friday INTEGER,
  saturday INTEGER,
  sunday INTEGER,
  start_date DATE,
  end_date DATE,
  CONSTRAINT pk_calendar PRIMARY KEY (id_service)
);

-- Add new column (foreign key) on table stop due conventional-relationship-stop-defined in-feed_info
ALTER TABLE stop
  ADD COLUMN feed_info_id_feed INTEGER;

-- Add foreign key constraint on table stop due conventional-relationship-stop-defined in-feed_info
ALTER TABLE stop ADD
  CONSTRAINT fk_stop_ref_feed_info
  FOREIGN KEY (feed_info_id_feed)
  REFERENCES feed_info(id_feed);

-- Add new column (foreign key) on table fare_rule due conventional-relationship-fare_rule-ruled by-fare_attribute
ALTER TABLE fare_rule
  ADD COLUMN fare_attribute_id_fare INTEGER;

-- Add foreign key constraint on table fare_rule due conventional-relationship-fare_rule-ruled by-fare_attribute
ALTER TABLE fare_rule ADD
  CONSTRAINT fk_fare_rule_ref_fare_attribute
  FOREIGN KEY (fare_attribute_id_fare)
  REFERENCES fare_attribute(id_fare);

-- Add new column (foreign key) on table route due conventional-relationship-route-defined by-agency
ALTER TABLE route
  ADD COLUMN agency_id_agency INTEGER;

-- Add foreign key constraint on table route due conventional-relationship-route-defined by-agency
ALTER TABLE route ADD
  CONSTRAINT fk_route_ref_agency
  FOREIGN KEY (agency_id_agency)
  REFERENCES agency(id_agency);

-- Add new column (foreign key) on table stop_time due conventional-relationship-stop-stop-stop_time
ALTER TABLE stop_time
  ADD COLUMN stop_id_stop INTEGER;

-- Add foreign key constraint on table stop_time due conventional-relationship-stop-stop-stop_time
ALTER TABLE stop_time ADD
  CONSTRAINT fk_stop_time_ref_stop
  FOREIGN KEY (stop_id_stop)
  REFERENCES stop(id_stop);

-- Add new column (foreign key) on table stop_time due conventional-relationship-stop_time-related to-trip
ALTER TABLE stop_time
  ADD COLUMN trip_id_trip INTEGER;

-- Add foreign key constraint on table stop_time due conventional-relationship-stop_time-related to-trip
ALTER TABLE stop_time ADD
  CONSTRAINT fk_stop_time_ref_trip
  FOREIGN KEY (trip_id_trip)
  REFERENCES trip(id_trip);

-- Add new column (foreign key) on table transfer due conventional-relationship-transfer-from-stop
ALTER TABLE transfer
  ADD COLUMN stop_id_stop INTEGER;

-- Add foreign key constraint on table transfer due conventional-relationship-transfer-from-stop
ALTER TABLE transfer ADD
  CONSTRAINT fk_transfer_ref_stop
  FOREIGN KEY (stop_id_stop)
  REFERENCES stop(id_stop);

-- Add new column (foreign key) on table agency due conventional-relationship-agency-specified in-feed_info
ALTER TABLE agency
  ADD COLUMN feed_info_id_feed INTEGER;

-- Add foreign key constraint on table agency due conventional-relationship-agency-specified in-feed_info
ALTER TABLE agency ADD
  CONSTRAINT fk_agency_ref_feed_info
  FOREIGN KEY (feed_info_id_feed)
  REFERENCES feed_info(id_feed);

-- Add new column (foreign key) on table zone due conventional-relationship-zone-defined in-feed_info
ALTER TABLE zone
  ADD COLUMN feed_info_id_feed INTEGER;

-- Add foreign key constraint on table zone due conventional-relationship-zone-defined in-feed_info
ALTER TABLE zone ADD
  CONSTRAINT fk_zone_ref_feed_info
  FOREIGN KEY (feed_info_id_feed)
  REFERENCES feed_info(id_feed);

-- Add new column (foreign key) on table trip due conventional-relationship-service-define-trip
ALTER TABLE trip
  ADD COLUMN service_id_service INTEGER;

-- Add foreign key constraint on table trip due conventional-relationship-service-define-trip
ALTER TABLE trip ADD
  CONSTRAINT fk_trip_ref_service
  FOREIGN KEY (service_id_service)
  REFERENCES service(id_service);

-- Add new column (foreign key) on table frequency due conventional-relationship-frequency-define-trip
ALTER TABLE frequency
  ADD COLUMN trip_id_trip INTEGER;

-- Add foreign key constraint on table frequency due conventional-relationship-frequency-define-trip
ALTER TABLE frequency ADD
  CONSTRAINT fk_frequency_ref_trip
  FOREIGN KEY (trip_id_trip)
  REFERENCES trip(id_trip);

-- Add new column (foreign key) on table trip due conventional-aggregation-route-trip
ALTER TABLE trip
  ADD COLUMN route_id_route INTEGER;

-- Add foreign key constraint on table trip due conventional-aggregation-route-trip
ALTER TABLE trip ADD
  CONSTRAINT fk_trip_ref_route
  FOREIGN KEY (route_id_route)
  REFERENCES route(id_route);

-- Add new column (foreign key) on table transfer due conventional-relationship-transfer-to-stop
ALTER TABLE transfer
  ADD COLUMN stop_id_stop INTEGER;

-- Add foreign key constraint on table transfer due conventional-relationship-transfer-to-stop
ALTER TABLE transfer ADD
  CONSTRAINT fk_transfer_ref_stop
  FOREIGN KEY (stop_id_stop)
  REFERENCES stop(id_stop);

-- Add new column (foreign key) on table trip_line due conventional-aggregation-trip-trip_line
ALTER TABLE trip_line
  ADD COLUMN trip_id_trip INTEGER;

-- Add foreign key constraint on table trip_line due conventional-aggregation-trip-trip_line
ALTER TABLE trip_line ADD
  CONSTRAINT fk_trip_line_ref_trip
  FOREIGN KEY (trip_id_trip)
  REFERENCES trip(id_trip);

-- Add new column (foreign key) on table calendar_date due conventional-relationship-calendar_date-define-service
ALTER TABLE calendar_date
  ADD COLUMN service_id_service INTEGER;

-- Add foreign key constraint on table calendar_date due conventional-relationship-calendar_date-define-service
ALTER TABLE calendar_date ADD
  CONSTRAINT fk_calendar_date_ref_service
  FOREIGN KEY (service_id_service)
  REFERENCES service(id_service);

-- Create table fare_rule_zone
CREATE TABLE fare_rule_zone (
  fare_rule_id_fare_rule INTEGER,
  zone_zone_id INTEGER,
  zone_id_feed INTEGER,
  CONSTRAINT pk_fare_rule_zone PRIMARY KEY (fare_rule_id_fare_rule,zone_zone_id,zone_id_feed)
);

-- Add foreign key constraint on table fare_rule_zone due conventional-relationship-fare_rule-dest-zone
ALTER TABLE fare_rule_zone ADD
  CONSTRAINT fk_fare_rule_zone_ref_fare_rule
  FOREIGN KEY (fare_rule_id_fare_rule)
  REFERENCES fare_rule(id_fare_rule);

-- Add foreign key constraint on table fare_rule_zone due conventional-relationship-fare_rule-dest-zone
ALTER TABLE fare_rule_zone ADD
  CONSTRAINT fk_fare_rule_zone_ref_zone
  FOREIGN KEY (zone_zone_id,zone_id_feed)
  REFERENCES zone(zone_id,id_feed);

-- Create table fare_rule_zone
CREATE TABLE fare_rule_zone (
  fare_rule_id_fare_rule INTEGER,
  zone_zone_id INTEGER,
  zone_id_feed INTEGER,
  CONSTRAINT pk_fare_rule_zone PRIMARY KEY (fare_rule_id_fare_rule,zone_zone_id,zone_id_feed)
);

-- Add foreign key constraint on table fare_rule_zone due conventional-relationship-fare_rule-contains-zone
ALTER TABLE fare_rule_zone ADD
  CONSTRAINT fk_fare_rule_zone_ref_fare_rule
  FOREIGN KEY (fare_rule_id_fare_rule)
  REFERENCES fare_rule(id_fare_rule);

-- Add foreign key constraint on table fare_rule_zone due conventional-relationship-fare_rule-contains-zone
ALTER TABLE fare_rule_zone ADD
  CONSTRAINT fk_fare_rule_zone_ref_zone
  FOREIGN KEY (zone_zone_id,zone_id_feed)
  REFERENCES zone(zone_id,id_feed);

-- Create table fare_rule_zone
CREATE TABLE fare_rule_zone (
  fare_rule_id_fare_rule INTEGER,
  zone_zone_id INTEGER,
  zone_id_feed INTEGER,
  CONSTRAINT pk_fare_rule_zone PRIMARY KEY (fare_rule_id_fare_rule,zone_zone_id,zone_id_feed)
);

-- Add foreign key constraint on table fare_rule_zone due conventional-relationship-fare_rule-orig-zone
ALTER TABLE fare_rule_zone ADD
  CONSTRAINT fk_fare_rule_zone_ref_fare_rule
  FOREIGN KEY (fare_rule_id_fare_rule)
  REFERENCES fare_rule(id_fare_rule);

-- Add foreign key constraint on table fare_rule_zone due conventional-relationship-fare_rule-orig-zone
ALTER TABLE fare_rule_zone ADD
  CONSTRAINT fk_fare_rule_zone_ref_zone
  FOREIGN KEY (zone_zone_id,zone_id_feed)
  REFERENCES zone(zone_id,id_feed);

-- Add new column (foreign key) on table fare_attribute due conventional-relationship-fare_attribute-defined by-agency
ALTER TABLE fare_attribute
  ADD COLUMN agency_id_agency INTEGER;

-- Add foreign key constraint on table fare_attribute due conventional-relationship-fare_attribute-defined by-agency
ALTER TABLE fare_attribute ADD
  CONSTRAINT fk_fare_attribute_ref_agency
  FOREIGN KEY (agency_id_agency)
  REFERENCES agency(id_agency);

-- Create table fare_rule_route
CREATE TABLE fare_rule_route (
  fare_rule_id_fare_rule INTEGER,
  route_id_route INTEGER,
  CONSTRAINT pk_fare_rule_route PRIMARY KEY (fare_rule_id_fare_rule,route_id_route)
);

-- Add foreign key constraint on table fare_rule_route due conventional-relationship-fare_rule-applied to-route
ALTER TABLE fare_rule_route ADD
  CONSTRAINT fk_fare_rule_route_ref_fare_rule
  FOREIGN KEY (fare_rule_id_fare_rule)
  REFERENCES fare_rule(id_fare_rule);

-- Add foreign key constraint on table fare_rule_route due conventional-relationship-fare_rule-applied to-route
ALTER TABLE fare_rule_route ADD
  CONSTRAINT fk_fare_rule_route_ref_route
  FOREIGN KEY (route_id_route)
  REFERENCES route(id_route);

-- Create table station_feed_info
CREATE TABLE station_feed_info (
  station_id_station INTEGER,
  feed_info_id_feed INTEGER,
  CONSTRAINT pk_station_feed_info PRIMARY KEY (station_id_station,feed_info_id_feed)
);

-- Add foreign key constraint on table station_feed_info due conventional-relationship-station-defined in-feed_info
ALTER TABLE station_feed_info ADD
  CONSTRAINT fk_station_feed_info_ref_station
  FOREIGN KEY (station_id_station)
  REFERENCES station(id_station);

-- Add foreign key constraint on table station_feed_info due conventional-relationship-station-defined in-feed_info
ALTER TABLE station_feed_info ADD
  CONSTRAINT fk_station_feed_info_ref_feed_info
  FOREIGN KEY (feed_info_id_feed)
  REFERENCES feed_info(id_feed);

-- Add new column (foreign key) on table service due conventional-relationship-calendar-define-service
ALTER TABLE service
  ADD COLUMN calendar_id_service INTEGER;

-- Add foreign key constraint on table service due conventional-relationship-calendar-define-service
ALTER TABLE service ADD
  CONSTRAINT fk_service_ref_calendar
  FOREIGN KEY (calendar_id_service)
  REFERENCES calendar(id_service);

**Comment by lizardoluis** [comment]
Oi @lcrcosta,
Está correta sim, mas ela depende dessa extensão aqui: https://github.com/lizardoluis/ast_postgis.
Basta instalar ela no seu PostgreSQL.
