### ISSUE TITLE
Utilizar o AST-PostGIS no Windows

### ISSUE THREAD

**Issue by lcrcosta** [lizardoluis/omtg-designer#21]
Luis, 
boa noite.

Você tem sugestão de como carregar sua extensão no Postgres em Windows?
Obrigado.

**Comment by lizardoluis** [comment]
Na verdade essa pergunta seria mais apropriada no repositório do [AST_PostGIS](https://github.com/lizardoluis/ast_postgis) 

Mas respondendo... não tenho ideia de como fazer isso!! Nunca nem tentei!!

No entanto, pelo que pesquisei rapidamente aqui na internet, vc pode tentar utilizar o [MinGW](http://mingw.org). Se caso consegui, faça por favor um pull request no repositório do AST_PostGIS colocando a instrução no README.md. Ai te dou os pontos em BDG.

**Comment by lizardoluis** [comment]
Vou fechar essa issue aqui, por não ser relacionada diretamente ao OMT-G Designer. Mas abrir uma nova, no repositório do AST_PostGIS: https://github.com/lizardoluis/ast_postgis/issues/2

**Comment by lcrcosta** [comment]
Ok. Obrigado.
Se eu tiver sucesso, retorno. 
Abr.,
Luiz Carlos R Costa, PMP® 

    Em Terça-feira, 23 de Maio de 2017 22:03, Luís Lizardo <notifications@github.com> escreveu:
 

 Vou fechar essa issue aqui, por não ser relacionada diretamente ao OMT-G Designer. Mas abrir uma nova, no repositório do AST_PostGIS: lizardoluis/ast_postgis#2—
