### ISSUE TITLE
Nome das Classes no editor de relacionamento

### ISSUE THREAD

**Issue by lcrcosta** [lizardoluis/omtg-designer#22]
Luis,

No modal do conector, a melhoria implantada de colocar os nomes das tabelas, está assim: "Cardinality A ([object Object]):" mesmo colocando nomes nas classes.
Abraço.

**Comment by lizardoluis** [comment]
Resolvido. Eu havia feito algumas refatorações e acabei gerando esse erro.
+ 0.5 pts em BDG

**Comment by lcrcosta** [comment]
ok. obrigado.
 
Abr.,
Luiz Carlos R Costa, PMP® 

    Em Terça-feira, 23 de Maio de 2017 21:41, Luís Lizardo <notifications@github.com> escreveu:
 

 Resolvido. Eu havia feito algumas refatorações e acabei gerando esse erro.   
   - 0.5 pts em BDG
