### ISSUE TITLE
A sintaxe geralmente é atualizada?

### ISSUE THREAD

**Issue by wm1981** [lizardoluis/omtg-designer#24]
Bom dia, não sou DBA, nem desenvolvedor, estou iniciando no Postgis e estive tentando modelar um banco espacial com o OMT-G Designer. De início tive problemas para executar a versão desktop, aparentemente devido a incompatibilidades com versão do Eclipse, Java, não sei bem. Posteriormente descobri a versão online.
Fiz a modelagem, gerei o gráfico e exportei o sql. Importei no pgAdmin4 e tive que especificar os esquemas para pode executar as querys. As colunas de geometria que iniciam com "ast_" dão erro, surge a mensagem de que a função não existe. No geral eu deletei o "ast_" e funcionou, porém, ao importar o arquivo com as querys de restrições (as relações entre as entidades) não consegui executar de jeito nenhum. De qualquer maneira que execute há sempre o erro "function ast_spatialrelationship() does not exist". Poderia me ajudar? Obrigado.

**Comment by lizardoluis** [comment]
Prezado, está correto sim, mas você precisa instalar o ast-postgis. https://github.com/lizardoluis/ast_postgis

Ele implementa tipos de dados avançados (semanticamente enriquecidos) e restrições de integridade espaciais. Que são os tipos e funções com prefixo ast que você notou. Caso queira ler mais sobre ele, dá uma olhada nesse paper: https://dl.acm.org/citation.cfm?id=3140020

**Comment by lizardoluis** [comment]
A propósito. Nao conheço a versão desktop que você citou. Ela deve ter sido desenvolvida por outro grupo.

**Comment by wm1981** [comment]
Obrigado pelo retorno Luis, eu vou olhar mais detalhes então. Não me lembro agora aonde vi essa versão, senão te enviaria o link. Essa instalação do ast-postgis eu faço no pgAdmin, é isso?
É só no linux ou é possível no Windows também?

Pelo que entendi da descrição, a sua ferramenta converte a sintaxe mais complexa em comandos mais simples... Há alguma lista com essas sintaxes? Gostaria de aprender, para o caso de precisar usar e não ter uma ferramenta que faça esse tipo de conversão. Tenho procurado nos manuais do post-gis, mas, como leigo, ainda não peguei o "x" da coisa.
Obrigado.

**Comment by lizardoluis** [comment]
Não, vc precisa instalar usando o terminal como diz aqui https://github.com/lizardoluis/ast_postgis#build-and-install. 

No windows é possível, mas não sei como. Você teria que verificar.

**Comment by wm1981** [comment]
Obrigado.

Em qui, 19 de abr de 2018 05:29, Luís Lizardo <notifications@github.com>
escreveu:
