### ISSUE TITLE
Não tem relacionamento espacial com restrição "Adjacente"

### ISSUE THREAD

**Issue by guilhermehrn** [lizardoluis/omtg-designer#25]
Eu não consegui encontrar um relacionamento espacial com a restrição "Adjacente". Segundo a EDGV relacionamento "Adjacente" é utilizado no sentido de vizinhança, ao lado de, contíguo.

**Comment by lizardoluis** [comment]
OMT-G considers a set of five basic spatial relationships between georeferenced classes, from which all others can be derived (Clementini 1993, Davis 2005): crosses, disjoint, overlaps, touches and within.  

http://www.bibliotecadigital.ufmg.br/dspace/bitstream/handle/1843/ESBF-ANZJZ3/luiseduardooliveiralizardo.pdf?sequence=1
